"""first generate table

Revision ID: 431154b2577b
Revises: 
Create Date: 2026-01-07 09:54:36.148964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431154b2577b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='员工薪资'))
    op.add_column('employee', sa.Column('bonus', sa.Integer(), nullable=False, comment='员工奖金'))
    op.add_column('employee', sa.Column('is_leave', sa.Boolean(), nullable=False, comment='员工是否离职，默认不离职'))
    op.add_column('employee', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gendervalue'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'gender')
    op.drop_column('employee', 'is_leave')
    op.drop_column('employee', 'bonus')
    op.drop_column('employee', 'salary')
    # ### end Alembic commands ###
