"""addnewcolumnentrydate

Revision ID: b7ac89dd0a3f
Revises: 431154b2577b
Create Date: 2026-01-07 10:18:25.970106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ac89dd0a3f'
down_revision: Union[str, Sequence[str], None] = '431154b2577b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('entry_date', sa.DateTime(), nullable=False, comment='入职时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'entry_date')
    # ### end Alembic commands ###
